# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e97df0e88c9f0cf7a6c49cc8b41712d913e05ec737c8b7a62ff90afbc3791e8635c4b0822e96b2f1666f5214d0920bdb6d1aa6544cd3e898cba32e1f1cfc584

test:
  secret_key_base: 2574f2551e8911e7da8b8327568dc269e236873d532b81987777536ff194e094c563ae7a89462dd8933f15048cff051bad90b751fc4f3b3ce6e98c482bfdc533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
